
from veridian.employee_requests import EMPLOYEE_REQUESTS
from veridian.tickets import TICKETS


def find_relevant_tickets(employee_name, request_text):
    """Find tickets related to the employee and request topic."""

    matches = []

    employee_last_name = employee_name.split()[-1].lower()
    request_words = set(request_text.lower().split())

    for ticket_id, ticket in TICKETS.items():
        ticket_employee = ticket["employee"].lower()
        ticket_issue = ticket["issue"].lower()

        same_employee = employee_last_name in ticket_employee

        topic_match = any(
            word in ticket_issue
            for word in request_words
            if len(word) > 3
        )

        if same_employee and topic_match:
            matches.append({
                "ticket_id": ticket_id,
                **ticket,
            })

    return matches


def get_request(request_id):
    """Get an employee request by ID."""

    return EMPLOYEE_REQUESTS.get(request_id)


def analyze_request(request_id):
    """Analyze a Veridian employee request."""

    request = get_request(request_id)

    if not request:
        return {
            "status": "error",
            "message": f"Request {request_id} was not found.",
        }

    employee = request["employee"]
    request_text = request["request"].lower()

    relevant_tickets = find_relevant_tickets(
        employee,
        request_text,
    )

    result = {
        "request_id": request_id,
        "employee": employee,
        "request": request["request"],
        "current_status": request["status"],
        "decision": "Needs clarification",
        "response": "",
        "sources": [],
        "tickets": relevant_tickets,
    }

    # --------------------------------------------------
    # PASSWORD RESET
    # --------------------------------------------------
    if "password" in request_text and (
        "locked" in request_text or "failed" in request_text
    ):
        result["decision"] = "Resolve"
        result["response"] = (
            "The employee should contact IT because the account has exceeded "
            "5 failed password attempts. IT can manually unlock the account. "
            "No approval is required."
        )
        result["sources"] = ["KB-01"]

    # --------------------------------------------------
    # GUEST WI-FI
    # --------------------------------------------------
    elif "guest wi-fi" in request_text:
        result["decision"] = "Resolve"
        result["response"] = (
            "Guest Wi-Fi credentials can be generated by any employee "
            "from the front-desk kiosk. Credentials are valid for 24 hours. "
            "No IT ticket is required."
        )
        result["sources"] = ["KB-07"]

    # --------------------------------------------------
    # VPN
    # --------------------------------------------------
    elif "vpn" in request_text:
        result["decision"] = "Needs clarification"
        result["response"] = (
            "VPN credentials expire every 90 days and must be renewed. "
            "Full-time employees receive VPN access automatically, while "
            "contractors require manager approval through the access request form. "
            "The employee's employment type is not provided."
        )
        result["sources"] = ["KB-02"]

    # --------------------------------------------------
    # LAPTOP
    # --------------------------------------------------
    elif "laptop" in request_text:
        result["decision"] = "Escalate"
        result["response"] = (
            "Laptop replacement depends on the laptop's age or a verified "
            "hardware failure. The Asset Management Policy states that company "
            "hardware follows a 4-year refresh cycle, while early replacement "
            "outside that cycle requires Finance sign-off in addition to IT approval."
        )
        result["sources"] = ["KB-03", "ASSET-POLICY"]

    # --------------------------------------------------
    # SOFTWARE INSTALLATION
    # --------------------------------------------------
    elif "install" in request_text or "software" in request_text:
        result["decision"] = "Escalate"
        result["response"] = (
            "Software outside the standard catalog requires IT Security review. "
            "The review takes 3–5 business days."
        )
        result["sources"] = ["KB-04"]

    # --------------------------------------------------
    # PRINTER
    # --------------------------------------------------
    elif "printer" in request_text:
        result["decision"] = "Resolve"
        result["response"] = (
            "Check the printer queue and restart the print spooler. "
            "If the problem continues, the ticket should include the printer asset tag."
        )
        result["sources"] = ["KB-05"]

    # --------------------------------------------------
    # EMAIL / MAILBOX
    # --------------------------------------------------
    elif "mailbox" in request_text or "email" in request_text:
        result["decision"] = "Needs clarification"
        result["response"] = (
            "The default mailbox quota is 25GB. The employee should archive old mail "
            "when approaching the limit. Any increase above 25GB requires manager "
            "approval and cannot exceed 50GB."
        )
        result["sources"] = ["KB-06"]

    # --------------------------------------------------
    # WFH EQUIPMENT
    # --------------------------------------------------
    elif "wfh" in request_text or "monitor" in request_text:
        result["decision"] = "Escalate"
        result["response"] = (
            "Employees working remotely more than 3 days per week are eligible "
            "for a one-time home office allowance. Manager sign-off and Finance "
            "processing are required. IT handles equipment shipping only after approval."
        )
        result["sources"] = ["KB-10"]

    # --------------------------------------------------
    # PHISHING / SECURITY
    # --------------------------------------------------
    elif "phishing" in request_text or "security" in request_text:
        result["decision"] = "Escalate"
        result["response"] = (
            "The security incident should be reported immediately to "
            "security@veridian-corp.example. Security incidents should not be "
            "forwarded to other employees."
        )
        result["sources"] = ["KB-09"]

    # --------------------------------------------------
    # EXPENSE SOFTWARE
    # --------------------------------------------------
    elif "expense" in request_text:
        result["decision"] = "Needs clarification"
        result["response"] = (
            "Expense software access is managed by Finance, not IT. "
            "IT can assist with login or technical issues once the account exists."
        )
        result["sources"] = ["KB-08"]

    # --------------------------------------------------
    # VAGUE REQUEST
    # --------------------------------------------------
    else:
        result["decision"] = "Ask follow-up"
        result["response"] = (
            "The request does not contain enough information to identify the "
            "issue or applicable policy. The employee should provide more details."
        )
        result["sources"] = []

    # --------------------------------------------------
    # EXISTING TICKET CHECK
    # --------------------------------------------------
    if relevant_tickets:
        active_tickets = [
            ticket
            for ticket in relevant_tickets
            if ticket["state"] == "Active"
        ]

        if active_tickets:
            result["existing_ticket_action"] = (
                "Do not create a duplicate ticket."
            )
            result["existing_active_tickets"] = active_tickets
        else:
            result["existing_ticket_action"] = (
                "No active matching ticket found."
            )
            result["existing_active_tickets"] = []

    else:
        result["existing_ticket_action"] = (
            "No matching ticket found."
        )
        result["existing_active_tickets"] = []

    return result
